import './globals.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import { Header } from '@/components/layouts/header';
import AppSessionProvider from '@/components/providers/app-session-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { getAppSession } from '@/lib/get-app-session';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getAppSession();

  return (
    <html lang="en">
      <body className={cn('min-h-screen font-sans antialiased', fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppSessionProvider session={session}>
            <NextTopLoader />
            <Header />
            {children}
          </AppSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
